development: &development
  adapter: postgresql
  database: sample_app
  username: russell
  password: password

test:
  adapter: postgresql
  database: sample_app_test
  username: russell
  password: password


